import { customerId,conversationId,contactId } from '../demo-data.js';
export const caseScenarios={kind:'cases',options:[['cases','6 · O agente precisa de você'],['cases-empty','6 · Nenhum caso'],['cases-loading','6 · Carregando casos'],['cases-error','6 · Erro nos casos'],['cases-permission','6 · Sem permissão']]};
caseScenarios.options.push(['cases-unique','6 · Clientes únicos no fuso']);
export const demoCase={id:'00000000-0000-4000-8000-000000000071',conversation_id:conversationId,contact_id:contactId,contact_name:'Marina Oliveira',agent_id:'00000000-0000-4000-8000-000000000072',title:'Desconto para 40 lembranças',summary:'Marina pediu 15% de desconto. O agente pode oferecer até 5% e escalou a decisão comercial.',blocker:'Autorizar um desconto fora da política do negócio',status:'open',revision:4,created_at:new Date(Date.now()-15*60000).toISOString()};
export function casesStage(scenario:string){if(scenario==='cases-error')return {isError:true};return {structuredContent:{customer_id:customerId,cases:{data:scenario==='cases-empty'?[]:[demoCase],meta:{total_count:scenario==='cases-empty'?0:1}},usage:{handoff:{conversations:24,handoffs:1},...(scenario==='cases-unique'?{unique_contacts_today:17,timezone:'America/Manaus'}:{})},user_id:'00000000-0000-4000-8000-000000000073',can_update:scenario!=='cases-permission'}};}
export async function casesTool(name:string,args:Record<string,any>,scenario:string){
  if(name==='ai_cases_update'){await new Promise(r=>setTimeout(r,400));return {structuredContent:{data:{...demoCase,...args,revision:5}}};}
  if(name==='list_messages'&&scenario.startsWith('cases'))return {structuredContent:{data:[{id:'case-message-client',direction:'inbound',created_at:new Date(Date.now()-16*60000).toISOString(),content:{text:{body:'Se eu fechar as 40 lembranças hoje, vocês conseguem fazer 15% de desconto?'}}},{id:'case-message-agent',direction:'outbound',created_at:demoCase.created_at,content:{text:{body:'Posso oferecer 5%. Para um desconto maior, vou pedir à equipe para avaliar com carinho.'}}}],paging:{next:null}}};
}
