const base = { language: 'pt_BR', status: 'APPROVED', category: 'UTILITY', waba_connection_id: '00000000-0000-4000-8000-000000000060' };
const body = { type: 'BODY', text: 'Marina, veja os detalhes das suas 40 lembranças no Ateliê das Águas.' };
const buttons = { type: 'BUTTONS', buttons: [{ type: 'URL', text: 'Ver orçamento', url: 'https://botozap.com.br/orcamentos/{{1}}' }, { type: 'PHONE_NUMBER', text: 'Ligar para o Ateliê', phone_number: '+5592999990010' }] };
const make = (n: number, name: string, components: any[], category = 'UTILITY') => ({ ...base, id: `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`, name, category, components });
export const completeTemplates = [
    make(401, 'orcamento_com_imagem', [{ type: 'HEADER', format: 'IMAGE' }, body, buttons]),
    make(402, 'orcamento_em_pdf', [{ type: 'HEADER', format: 'DOCUMENT' }, body, buttons]),
    make(403, 'seu_pedido_em_video', [{ type: 'HEADER', format: 'VIDEO' }, body, buttons]),
    make(404, 'retirada_no_atelie', [{ type: 'HEADER', format: 'LOCATION' }, body, { type: 'BUTTONS', buttons: [{ type: 'QUICK_REPLY', text: 'Vou buscar' }] }]),
    make(405, 'verificar_acesso', [{ type: 'BODY', text: 'Seu código de verificação é {{1}}. Não compartilhe este código.' }, { type: 'FOOTER', text: 'Este código expira em 5 minutos.', code_expiration_minutes: 5 }, { type: 'BUTTONS', buttons: [{ type: 'OTP', otp_type: 'COPY_CODE', text: 'Copiar código' }] }], 'AUTHENTICATION'),
    make(406, 'verificar_acesso_one_tap', [{ type: 'BODY', text: '{{1}} é seu código de verificação. Não compartilhe com ninguém.' }, { type: 'BUTTONS', buttons: [{ type: 'OTP', otp_type: 'ONE_TAP', text: 'Preencher código', autofill_text: 'Preencher código' }] }], 'AUTHENTICATION'),
    make(407, 'colecao_das_aguas', [{ type: 'BODY', text: '{{1}}, escolhemos duas ideias para suas lembranças.' }, { type: 'CAROUSEL', cards: ['Rio', 'Floresta'].map(text => ({ components: [{ type: 'HEADER', format: 'IMAGE' }, { type: 'BODY', text: `Coleção ${text} · {{1}} unidades` }, { type: 'BUTTONS', buttons: [{ type: 'QUICK_REPLY', text: 'Quero esta' }, { type: 'URL', text: 'Ver detalhes', url: 'https://botozap.com.br/colecoes/{{1}}' }] }] })) }], 'MARKETING'),
    make(408, 'oferta_da_colecao', [{ type: 'HEADER', format: 'IMAGE' }, { type: 'BODY', text: '{{nome}}, use o código {{cupom}} na sua próxima encomenda.' }, { type: 'LIMITED_TIME_OFFER', limited_time_offer: { text: 'Condição especial de hoje', has_expiration: true } }, { type: 'BUTTONS', buttons: [{ type: 'COPY_CODE' }, { type: 'URL', text: 'Ver condição', url: 'https://botozap.com.br/ofertas/{{1}}' }] }], 'MARKETING'),
    make(409, 'personalize_seu_pedido', [{ type: 'BODY', text: 'Escolha os acabamentos das suas lembranças.' }, { type: 'BUTTONS', buttons: [{ type: 'FLOW', text: 'Personalizar pedido', flow_id: '123456789', flow_action: 'navigate', navigate_screen: 'ACABAMENTOS' }] }]),
    make(410, 'veja_nosso_catalogo', [{ type: 'BODY', text: 'Marina, nossa nova coleção está no catálogo.' }, { type: 'BUTTONS', buttons: [{ type: 'CATALOG', text: 'Ver catálogo' }] }], 'MARKETING'),
    make(411, 'cupom_para_voce', [{ type: 'BODY', text: '{{nome}}, aqui está seu código {{cupom}} para a próxima encomenda.', example: { body_text_named_params: [{ param_name: 'nome', example: 'Marina' }, { param_name: 'cupom', example: 'AGUAS10' }] } }, { type: 'BUTTONS', buttons: [{ type: 'COPY_CODE' }, { type: 'URL', text: 'Usar código', url: 'https://botozap.com.br/ofertas/{{1}}' }] }], 'MARKETING'),
];
export const completeTemplateOptions = [['template-image', '4 · Imagem'], ['template-document', '4 · Documento'], ['template-video', '4 · Vídeo'], ['template-location', '4 · Localização'], ['template-auth', '4 · Autenticação copiar'], ['template-one-tap', '4 · Autenticação one-tap'], ['template-carousel', '4 · Carrossel'], ['template-offer', '4 · Oferta limitada'], ['template-flow', '4 · Formulário (Flow)'], ['template-catalog', '4 · Catálogo'], ['template-named', '4 · Variáveis nomeadas + cupom']];
export function completeTemplateContext(scenario: string) {
    const index = completeTemplateOptions.findIndex(([id]) => id === scenario);
    const t = completeTemplates[index];
    const suggestions: Record<string, Record<string, string>> = {};
    for (const t of completeTemplates) {
        suggestions[t.id] = { header_media_id: '123456789012345', header_filename: t.name + '.pdf', header_latitude: '-3.1316', header_longitude: '-60.0234', header_name: 'Ateliê das Águas', header_address: 'Centro · Manaus', body_1: t.category === 'AUTHENTICATION' ? '123456' : 'Marina', body_nome: 'Marina', body_cupom: 'AGUAS10', button_0_code: 'AGUAS10', button_1_1: 'colecao-das-aguas', button_0_1: 'marina-40', button_0_token: 'pedido-marina-40', button_0_data: '{"contato":"Marina"}', button_0_action: '{"thumbnail_product_retailer_id":"colecao-das-aguas"}', limited_time_offer_expiration: new Date(Date.now() + 8 * 3600000).toISOString(), card_0_header_media_id: '123456789012341', card_1_header_media_id: '123456789012342', card_0_body_1: '40', card_1_body_1: '40', card_0_button_0_payload: 'Quero coleção Rio', card_1_button_0_payload: 'Quero coleção Floresta', card_0_button_1_1: 'rio', card_1_button_1_1: 'floresta' };
    }
    return { preferred_template_id: t?.id, suggested_values: suggestions, media_metadata: { header: { filename: scenario === 'template-document' ? 'Orçamento Marina.pdf' : scenario === 'template-video' ? 'Detalhes do acabamento.mp4' : 'Coleção das Águas.jpg', file_size: scenario === 'template-video' ? 8 * 1024 * 1024 : 512 * 1024 }, card_0_header: { filename: 'Coleção Rio.jpg', file_size: 300 * 1024 }, card_1_header: { filename: 'Coleção Floresta.jpg', file_size: 400 * 1024 } } };
}
