import {afterEach,expect,it,vi} from 'vitest';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {InMemoryTransport} from '@modelcontextprotocol/sdk/inMemory.js';
import {buildServer} from '../src/server.js';
import {fullAccessIdentity} from './helpers/identity.js';
import {appMessages} from './fixtures/app-messages.js';
import {messagePreview,alertCopy,groupInbox} from '../src/agent-inbox.js';
vi.mock('node:fs/promises',async original=>({...await original<any>(),readFile:vi.fn(async()=>'<main id="app"></main>')}));
const id1='00000000-0000-4000-8000-000000000001',id2='00000000-0000-4000-8000-000000000011';
const clients:Client[]=[];afterEach(async()=>{await Promise.all(clients.splice(0).map(c=>c.close()));});
async function connect(count:number){const requests:URL[]=[];const fetch=vi.fn(async(input:RequestInfo|URL)=>{
 const u=new URL(String(input));requests.push(u);const path=u.pathname;const customer=u.searchParams.get('customer_id');const second=customer===id2;const conv=second?'00000000-0000-4000-8000-000000000013':appMessages[0].conversation_id;
 if(path.endsWith('/customers')){const page=Number(u.searchParams.get('page'));return Response.json({data:[{id:page===1?id1:id2,name:page===1?'Ateliê':'Café'}],meta:{page,per_page:100,total_count:count,total_pages:count}});}
 if(path.includes('/ai/')){expect([id1,id2]).toContain(customer);const status=u.searchParams.get('status');const rows=path.endsWith('/alerts')&&status==='acknowledged'?[{id:'alert-'+customer,conversation_id:conv,kind:'manipulation_detected',detail:'Mensagem retida (authority_claim)',status:'acknowledged',severity:'critical',created_at:appMessages[0].created_at}]:[];if(path.endsWith('/usage'))return Response.json({data:{unique_contacts_today:0,timezone:'America/Sao_Paulo'}});return Response.json({data:rows,meta:{page:1,per_page:100,total_count:rows.length,total_pages:1}});}
 if(path.endsWith('/conversations')){expect(u.searchParams.get('agent_paused')).toBe('true');expect([id1,id2]).toContain(customer);return Response.json({data:[{id:conv,contact:{name:second?'Sâmia':'Fernando'},agent_paused_at:appMessages[0].created_at}],paging:{next:null,cursors:{after:null}}});}
 if(path.endsWith('/messages')){expect([...u.searchParams.keys()].sort()).toEqual(['conversation_id','direction','limit','sort']);expect(u.searchParams.get('direction')).toBe('inbound');expect(u.searchParams.get('sort')).toBe('created_at');expect(u.searchParams.get('limit')).toBe('1');return Response.json({data:[appMessages[0]],paging:{next:null,cursors:{after:null}}});}
 throw new Error('Unexpected API route '+path);
 });const server=await buildServer({apiKey:'bz_live_test',uiEnabled:true,baseUrl:'https://api.test/v1',fetch},fullAccessIdentity);const client=new Client({name:'contract',version:'1'},{capabilities:{extensions:{'io.modelcontextprotocol/ui':{mimeTypes:['text/html;profile=mcp-app']}}} as any});const [ct,st]=InMemoryTransport.createLinkedPair();await Promise.all([server.connect(st),client.connect(ct)]);clients.push(client);return {client,requests};}
it.each([1,2])('no customer_id aggregates %s authorized businesses using readonly paginated discovery',async count=>{
 const {client,requests}=await connect(count);const tool=(await client.listTools()).tools.find(t=>t.name==='open_agent_cases')!;expect(tool.inputSchema.required||[]).not.toContain('customer_id');expect(tool.description).toContain('nunca abra open_botozap');const result=await client.callTool({name:'open_agent_cases',arguments:{}});expect(result.isError,JSON.stringify(result)).not.toBe(true);expect(result.structuredContent).toMatchObject({customer_id:count===1?id1:null,summary:{unique_items:count,alerts_unresolved:count,paused_conversations:count,businesses:count,open_cases:0}});const data=result.structuredContent as any;expect(data.paused.data[0].latest_customer_preview).toBe('Vocês conseguem entregar até sexta?');expect(data.alerts.data[0].customer_name).toBe('Ateliê');if(count===2)expect(data.paused.data[1].customer_name).toBe('Café');expect(JSON.parse((result.content as any)[0].text).summary.unique_items).toBe(count);expect(requests.filter(u=>u.pathname.endsWith('/customers'))).toHaveLength(count);
});
it('an explicit business is forwarded and avoids discovery',async()=>{const {client,requests}=await connect(2);const result=await client.callTool({name:'open_agent_cases',arguments:{customer_id:id1}});expect(result.isError).not.toBe(true);expect(requests.some(u=>u.pathname.endsWith('/customers'))).toBe(false);expect(result.structuredContent).toMatchObject({summary:{businesses:1,unique_items:1}});});
it('extracts actual serialized content and gives every non-text/empty/revoked message a label',()=>{expect(appMessages.map(messagePreview)).toEqual(['Vocês conseguem entregar até sexta?','Veja esta referência.','Áudio','Documento','Mensagem sem texto','Ainda estou aguardando.','Mensagem removida']);});
it('translates manipulation reasons and never exposes raw unknown codes or details',()=>{const known=alertCopy({kind:'manipulation_detected',detail:'Mensagem retida (authority_claim).'});expect(known.detail).toContain('alegou ser o dono');expect(known.detail).not.toContain('authority_claim');const unknown=alertCopy({kind:'internal_foo',detail:'unsafe_secret_failure'});expect(unknown.title).toBe('Alerta aguardando revisão');expect(unknown.detail).not.toMatch(/unsafe_secret|internal_foo/);});
it('groups alerts, paused state and cases by conversation while preserving independent items without a conversation',()=>{const rows=groupInbox({alerts:{data:[{id:'a',conversation_id:'c',status:'acknowledged',severity:'critical'},{id:'standalone',status:'open'}]},paused:{data:[{id:'c',agent_paused_at:'2026-10-01',contact:{name:'Fernando'}}]},cases:{data:[{id:'case',conversation_id:'c',status:'open',customer_id:id1}]}});expect(rows).toHaveLength(2);expect(rows[0]).toMatchObject({severity:'critical',agent_paused_at:'2026-10-01',primary_case:{id:'case'},contact:{name:'Fernando'}});expect(rows[0].alerts).toHaveLength(1);});
