import { contactLabel, formatPhone } from '../ui-helpers.js';
import type { Bridge } from '../panel.js';
import { shell,node,button,call,ScreenError,skeleton,type Row } from './screen-kit.js';
export function mountBooking(root:HTMLElement,bridge:Bridge) {
  const ui=shell(root,'Marcar horário','Escolha um horário que funcione');skeleton(ui.content);
  let context:Row, selected:Row, frozen=false,busy=false,key='',noticeKey='',owner='Responsável do horário';
  const fmt=(value:string,options:Intl.DateTimeFormatOptions)=>new Intl.DateTimeFormat('pt-BR',{timeZone:context.availability.time_zone,...options}).format(new Date(value));
  const noticeText=()=>`${context.conversation.contact?.name?.split(' ')[0]??'Olá'}, seu horário para ${context.service.name} ficou marcado para ${fmt(selected.starts_at,{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}. Até lá!`;
  function confirm(slot:Row){if(frozen)return;selected=slot;key=crypto.randomUUID();noticeKey='';const meta=node('dl','','screen-metadata');for(const [name,value] of [['Contato',contactLabel(context.conversation.contact)],['Serviço',context.service.name],['Horário',`${fmt(slot.starts_at,{weekday:'long',day:'numeric',month:'short'})} · ${fmt(slot.starts_at,{hour:'2-digit',minute:'2-digit'})}–${fmt(slot.ends_at,{hour:'2-digit',minute:'2-digit'})}`],['Com',owner]])meta.append(node('dt',name),node('dd',value));
    ui.content.replaceChildren(meta,node('p','Aviso ao cliente','eyebrow'),node('p',noticeText(),'screen-preview'));ui.actions.replaceChildren(button('Outro horário',()=>render()),button('Confirmar',()=>void book(),true));ui.state('Confirmando',`Confirmar marca o compromisso e envia este aviso pelo WhatsApp.${context.meeting_requested?' O Meet depende de uma conexão ativa do responsável.':''}`);
  }
  function render(){ui.actions.replaceChildren();const container=node('div','','booking-days');container.setAttribute('role','region');container.setAttribute('aria-label','Horários disponíveis');container.tabIndex=0;
    const now=fmt(new Date().toISOString(),{year:'numeric',month:'numeric',day:'numeric'});const tomorrow=fmt(new Date(Date.now()+86400000).toISOString(),{year:'numeric',month:'numeric',day:'numeric'});
    const days=new Map<string,Row[]>();for(const slot of [...context.availability.slots].sort((a,b)=>Date.parse(a.starts_at)-Date.parse(b.starts_at)).slice(0,8)){const date=fmt(slot.starts_at,{year:'numeric',month:'numeric',day:'numeric'});days.set(date,[...(days.get(date)??[]),slot]);}
    for(const [date,slots]of days){const section=node('section','','booking-day');const title=node('h2',`${date===now?'Hoje':date===tomorrow?'Amanhã':fmt(slots[0].starts_at,{weekday:'long'})}, ${fmt(slots[0].starts_at,{day:'numeric',month:'short'})}`);section.append(title);const strip=node('div','','booking-day-slots');for(const slot of slots){const card=node('article','','slot-card');card.append(node('strong',`${fmt(slot.starts_at,{hour:'2-digit',minute:'2-digit'})}–${fmt(slot.ends_at,{hour:'2-digit',minute:'2-digit'})}`),node('p',owner),node('p',context.meeting_requested?'Com Meet':'Atendimento presencial'),button('Marcar',()=>confirm(slot)));strip.append(card);}section.append(strip);container.append(section);}
    ui.content.replaceChildren(node('p',`${context.service.name} · ${context.service.duration_minutes} min`,'muted'),container);ui.state('Disponível',`Horários no fuso ${context.availability.time_zone}. A disponibilidade será conferida novamente ao confirmar.`);
  }
  async function book(){if(busy||frozen)return;busy=true;frozen=true;ui.actions.replaceChildren();ui.state('Marcando','Conferindo o horário antes de marcar…');let attempted=false,created=false;
    try{const fresh=(await call(bridge,'get_appointment_availability',context.query)).data;if(!fresh.slots.some((s:Row)=>s.starts_at===selected.starts_at&&s.ends_at===selected.ends_at))throw new ScreenError('Este horário deixou de estar disponível. Escolha outro.','rejected');
      attempted=true;const result=await call(bridge,'create_appointment',{contact_id:context.conversation.contact_id,conversation_id:context.conversation.id,service_id:context.service.id,owner_user_id:context.query.owner_user_id,title:context.service.name,scheduled_at:selected.starts_at,ends_at:selected.ends_at,time_zone:context.availability.time_zone,status:'confirmed',meeting_requested:context.meeting_requested,idempotency_key:key});if(!result.data?.id)throw new Error('Compromisso sem recibo.');created=true;
      const conv=(await call(bridge,'get_conversation',{id:context.conversation.id})).data;if(conv.contact_id!==context.conversation.contact_id||conv.phone_number_id!==context.conversation.phone_number_id)throw new Error('Destino mudou; aviso não enviado.');
      if(!Number.isFinite(Date.parse(conv.window_expires_at))||Date.parse(conv.window_expires_at)<=Date.now()||conv.status!=='active'){ui.state('Marcado',conv.channel==='instagram'?'Compromisso criado; envie o aviso pelo painel BotoZap quando a conversa permitir.':'Compromisso criado. A janela fechou; o aviso não foi enviado. Use um template aprovado para avisar o cliente.');return;}
      noticeKey=(await call(bridge,'prepare_send_intent',{})).idempotency_key;const receipt=await call(bridge,'reply_to_conversation',{conversation_id:conv.id,text:{body:noticeText()},idempotency_key:noticeKey});if(!receipt.id&&!receipt.wamid)throw new Error('Recibo do aviso incompleto.');ui.state('Marcado','Compromisso criado e aviso aceito pelo BotoZap; aceite não confirma entrega ou leitura.');
    }catch(error){const e=error as ScreenError;if(created){ui.state('Marcado · confira o aviso',`O compromisso foi criado, mas o aviso não foi confirmado: ${e.message} Confira o histórico; não marque novamente.`);}else if(!attempted||e.outcome==='rejected'){frozen=false;ui.state('Recusado',e.message);ui.actions.append(button('Escolher outro horário',()=>render()));}else ui.state('Incerto','Resultado da marcação não confirmado. Confira a agenda antes de repetir; os dados e a chave foram preservados.');}
    finally{busy=false;void bridge.context({conversation_id:context.conversation.id,appointment_intent:key,notice_intent:noticeKey,state:root.dataset.state}).catch(()=>{});}
  }
  async function load(result:Row){if(result.isError){ui.content.replaceChildren();ui.state('Erro','Não foi possível consultar a agenda. Confira o acesso ou consulte novamente pelo assistente.');return;}context=result.structuredContent;if(!context.availability?.slots?.length){ui.content.replaceChildren(node('h2','Sem horários livres neste período'),node('p','Peça ao assistente para consultar outro dia ou responsável.','muted'));ui.state('Sem horários');return;}
    try{const users=await call(bridge,'list_users',{});owner=users.data.find((u:Row)=>(u.user_id===context.query.owner_user_id||u.id===context.query.owner_user_id))?.name??owner;}catch{}render();}
  return {...ui,bootstrap(result:Row){void load(result);}};
}
