// Generated by capture-message-contract.mjs from actual app serializeMessage/channelFields.
export const provenance=[
  {
    "path": "src/app/api/v1/messages/serialize.ts",
    "sha256": "2e2f21540938866e1605f99c657718f87a42a38cdaa6b12a249e265499f6d1b3"
  },
  {
    "path": "src/lib/api/channel.ts",
    "sha256": "e062981aa5e319de2695492470061f0e89509a16052b98d887b13b065ea23c2b"
  }
];
export const appMessages=[
  {
    "id": "00000000-0000-4000-8000-000000000200",
    "wamid": "wamid.fixture.0",
    "external_id": "wamid.fixture.0",
    "channel": "whatsapp",
    "channel_account": {
      "id": "00000000-0000-4000-8000-000000000010",
      "channel": "whatsapp",
      "display": "+5511989669559"
    },
    "conversation_id": "00000000-0000-4000-8000-000000000003",
    "phone_number_id": "00000000-0000-4000-8000-000000000004",
    "contact_id": "00000000-0000-4000-8000-000000000002",
    "direction": "inbound",
    "type": "text",
    "status": "received",
    "source": "customer",
    "content": {
      "body": "Vocês conseguem entregar até sexta?"
    },
    "context": null,
    "error": null,
    "has_media": false,
    "revoked_at": null,
    "event_at": "2026-10-01T12:00:00Z",
    "wa_timestamp": null,
    "created_at": "2026-10-01T12:00:00Z"
  },
  {
    "id": "00000000-0000-4000-8000-000000000201",
    "wamid": "wamid.fixture.1",
    "external_id": "wamid.fixture.1",
    "channel": "whatsapp",
    "channel_account": {
      "id": "00000000-0000-4000-8000-000000000010",
      "channel": "whatsapp",
      "display": "+5511989669559"
    },
    "conversation_id": "00000000-0000-4000-8000-000000000003",
    "phone_number_id": "00000000-0000-4000-8000-000000000004",
    "contact_id": "00000000-0000-4000-8000-000000000002",
    "direction": "inbound",
    "type": "image",
    "status": "received",
    "source": "customer",
    "content": {
      "caption": "Veja esta referência."
    },
    "context": null,
    "error": null,
    "has_media": true,
    "revoked_at": null,
    "event_at": "2026-10-01T12:00:00Z",
    "wa_timestamp": null,
    "created_at": "2026-10-01T12:00:00Z"
  },
  {
    "id": "00000000-0000-4000-8000-000000000202",
    "wamid": "wamid.fixture.2",
    "external_id": "wamid.fixture.2",
    "channel": "whatsapp",
    "channel_account": {
      "id": "00000000-0000-4000-8000-000000000010",
      "channel": "whatsapp",
      "display": "+5511989669559"
    },
    "conversation_id": "00000000-0000-4000-8000-000000000003",
    "phone_number_id": "00000000-0000-4000-8000-000000000004",
    "contact_id": "00000000-0000-4000-8000-000000000002",
    "direction": "inbound",
    "type": "audio",
    "status": "received",
    "source": "customer",
    "content": {},
    "context": null,
    "error": null,
    "has_media": true,
    "revoked_at": null,
    "event_at": "2026-10-01T12:00:00Z",
    "wa_timestamp": null,
    "created_at": "2026-10-01T12:00:00Z"
  },
  {
    "id": "00000000-0000-4000-8000-000000000203",
    "wamid": "wamid.fixture.3",
    "external_id": "wamid.fixture.3",
    "channel": "whatsapp",
    "channel_account": {
      "id": "00000000-0000-4000-8000-000000000010",
      "channel": "whatsapp",
      "display": "+5511989669559"
    },
    "conversation_id": "00000000-0000-4000-8000-000000000003",
    "phone_number_id": "00000000-0000-4000-8000-000000000004",
    "contact_id": "00000000-0000-4000-8000-000000000002",
    "direction": "inbound",
    "type": "document",
    "status": "received",
    "source": "customer",
    "content": {},
    "context": null,
    "error": null,
    "has_media": true,
    "revoked_at": null,
    "event_at": "2026-10-01T12:00:00Z",
    "wa_timestamp": null,
    "created_at": "2026-10-01T12:00:00Z"
  },
  {
    "id": "00000000-0000-4000-8000-000000000204",
    "wamid": "wamid.fixture.4",
    "external_id": "wamid.fixture.4",
    "channel": "whatsapp",
    "channel_account": {
      "id": "00000000-0000-4000-8000-000000000010",
      "channel": "whatsapp",
      "display": "+5511989669559"
    },
    "conversation_id": "00000000-0000-4000-8000-000000000003",
    "phone_number_id": "00000000-0000-4000-8000-000000000004",
    "contact_id": "00000000-0000-4000-8000-000000000002",
    "direction": "inbound",
    "type": "text",
    "status": "received",
    "source": "customer",
    "content": {},
    "context": null,
    "error": null,
    "has_media": false,
    "revoked_at": null,
    "event_at": "2026-10-01T12:00:00Z",
    "wa_timestamp": null,
    "created_at": "2026-10-01T12:00:00Z"
  },
  {
    "id": "00000000-0000-4000-8000-000000000205",
    "wamid": "wamid.fixture.5",
    "external_id": "wamid.fixture.5",
    "channel": "whatsapp",
    "channel_account": {
      "id": "00000000-0000-4000-8000-000000000010",
      "channel": "whatsapp",
      "display": "+5511989669559"
    },
    "conversation_id": "00000000-0000-4000-8000-000000000003",
    "phone_number_id": "00000000-0000-4000-8000-000000000004",
    "contact_id": "00000000-0000-4000-8000-000000000002",
    "direction": "inbound",
    "type": "text",
    "status": "received",
    "source": "customer",
    "content": {
      "text": "Ainda estou aguardando."
    },
    "context": null,
    "error": null,
    "has_media": false,
    "revoked_at": null,
    "event_at": "2026-10-01T12:00:00Z",
    "wa_timestamp": null,
    "created_at": "2026-10-01T12:00:00Z"
  },
  {
    "id": "00000000-0000-4000-8000-000000000206",
    "wamid": "wamid.fixture.6",
    "external_id": "wamid.fixture.6",
    "channel": "whatsapp",
    "channel_account": {
      "id": "00000000-0000-4000-8000-000000000010",
      "channel": "whatsapp",
      "display": "+5511989669559"
    },
    "conversation_id": "00000000-0000-4000-8000-000000000003",
    "phone_number_id": "00000000-0000-4000-8000-000000000004",
    "contact_id": "00000000-0000-4000-8000-000000000002",
    "direction": "inbound",
    "type": "text",
    "status": "received",
    "source": "customer",
    "content": {
      "body": "Conteúdo removido"
    },
    "context": null,
    "error": null,
    "has_media": false,
    "revoked_at": "2026-10-01T12:01:00Z",
    "event_at": "2026-10-01T12:00:00Z",
    "wa_timestamp": null,
    "created_at": "2026-10-01T12:00:00Z"
  }
];
