import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import {mkdir,rename,writeFile,readdir,unlink} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const dir=fileURLToPath(new URL('../web/screenshots/',import.meta.url));await mkdir(dir,{recursive:true});
const routes=['template','template-image','template-document','template-video','template-location','template-auth','template-one-tap','template-carousel','template-offer','template-catalog','template-named'];
const browser=await chromium.launch();const results=[];
try{for(const theme of ['light','dark'])for(const [device,width,height]of [['desktop',1440,1050],['mobile',390,844]]){
 if(process.argv.includes('--mobile-only')&&device!=='mobile')continue;
 for(const route of routes){const video=theme==='dark'&&device==='desktop';const context=await browser.newContext({viewport:{width,height},timezoneId:'America/Manaus',reducedMotion:'reduce',...(video?{recordVideo:{dir,size:{width,height}}}:{})});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const external=[];page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:4173/'))external.push(r.url());});const frame=()=>page.frameLocator('iframe').last();
  await page.goto(`http://127.0.0.1:4173/chat?theme=${theme}&scenario=${route}`);await frame().getByRole('button',{name:'Usar template aprovado',exact:true}).click();await frame().locator('#approved-template').waitFor();await frame().locator('#app[data-state=Rascunho]').waitFor();await frame().locator('.template-bubble').first().scrollIntoViewIfNeeded();
  async function capture(step){const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(axe.violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)})),[],`${route}/${step} AA`);assert.deepEqual(errors,[]);assert.deepEqual(external,[],'No external media/font/request');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'No host overflow');assert.equal(await page.frames().at(-1).evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'No app overflow');if(video)await page.waitForTimeout(1600);const file=`4a-${route}-${step}-${device}-${theme}.png`;await page.screenshot({path:`${dir}/${file}`});results.push({file,axeViolations:0,externalRequests:0});console.log(file);}
  await capture('previa');await frame().getByRole('button',{name:'Revisar envio',exact:true}).click();await capture('confirmacao');await frame().getByRole('button',{name:'Enviar template',exact:true}).click();await frame().locator('#app[data-state=Aceito]').waitFor();if(video){await capture('aceito');await page.waitForTimeout(1800);}const recorded=page.video();await context.close();if(video)await rename(await recorded.path(),`${dir}/roteiro-4a-${route}-desktop-dark.webm`);
 }

 // Negative catalogue fixture injected exclusively into the simulated MCP host.
 {const context=await browser.newContext({viewport:{width,height},reducedMotion:'reduce'});const page=await context.newPage();
 await page.addInitScript(()=>{if(window!==window.top)return;window.addEventListener('message',event=>{
  const request=event.data;if(request?.method!=='tools/call'||request.params?.name!=='list_templates')return;
  event.stopImmediatePropagation();const result={content:[],structuredContent:{data:[{id:'00000000-0000-4000-8000-000000000061',name:'template_removido',language:'pt_BR',status:'APPROVED',components:[{type:'BODY',text:'Não exibir esta mensagem'},{type:'BUTTONS',buttons:[{type:'FLOW',text:'Não exibir este botão'}]}]}],meta:{total_pages:1}}};event.source.postMessage({jsonrpc:'2.0',id:request.id,result},'*');
 },true);});await page.goto(`http://127.0.0.1:4173/chat?theme=${theme}&scenario=template`);
 const frame=page.frameLocator('iframe').last();await frame.getByRole('button',{name:'Usar template aprovado',exact:true}).click();await frame.locator('#app[data-state="Não suportado"]').waitFor();assert.equal(await frame.getByRole('button').count(),0);assert.equal(await frame.locator('input,.template-bubble,.template-client-button').count(),0);await frame.getByText('Este template usa WhatsApp Flows, que não fazem parte do BotoZap. Use outro template aprovado.',{exact:true}).waitFor();await capture(page,'template-nao-suportado');await context.close();}
 for(const route of ['booking','cases','cases-unique']){const video=route==='booking'&&theme==='dark'&&device==='desktop';const context=await browser.newContext({viewport:{width,height},timezoneId:'America/Manaus',reducedMotion:'reduce',...(video?{recordVideo:{dir,size:{width,height}}}:{})});const page=await context.newPage();const frame=()=>page.frameLocator('iframe').last();await page.goto(`http://127.0.0.1:4173/chat?theme=${theme}&scenario=${route}`);await frame().locator('#app[data-state]').waitFor();await frame().getByRole('button',{name:route==='booking'?'Marcar':'Assumir',exact:true}).first().waitFor();await capture(page,`${route}-agrupado`);if(video){await page.waitForTimeout(1800);await frame().getByRole('button',{name:'Marcar',exact:true}).first().click();await page.waitForTimeout(1800);await capture(page,'booking-confirmacao');await frame().getByRole('button',{name:'Confirmar',exact:true}).click();await frame().locator('#app[data-state=Marcado]').waitFor();await page.waitForTimeout(2400);}const recorded=page.video();await context.close();if(video)await rename(await recorded.path(),`${dir}/roteiro-4a-booking-desktop-dark.webm`);}
 for(const host of ['chatgpt','generic','none'])for(const view of ['card','radar']){const context=await browser.newContext({viewport:{width,height},timezoneId:'America/Manaus',reducedMotion:'reduce'});const page=await context.newPage();await page.goto(`http://127.0.0.1:4173/chat?theme=${theme}&host=${host}`);await page.waitForSelector('html[data-demo-ready=true]');const input=page.locator('#prompt');await input.fill(view==='radar'?'Abra o Radar':'Prepare uma resposta para Marina');await page.locator('#composer').evaluate(f=>f.requestSubmit());if(host!=='none'){const frame=page.frameLocator('iframe').last();await frame.locator(view==='card'?'#card-preview':'#app[data-mode=fullscreen]').waitFor();}else await page.locator('.plain-tool-response').last().waitFor();await capture(page,`host-${host}-${view}`);await context.close();}
 async function capture(page,name){const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(axe.violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)})),[],`${name} AA`);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const file=`4a-${name}-${device}-${theme}.png`;await page.screenshot({path:`${dir}/${file}`});results.push({file,axeViolations:0});console.log(file);}
}}finally{await browser.close();for(const file of await readdir(dir))if(/^[a-f0-9]{32}\.webm$/.test(file))await unlink(`${dir}/${file}`);}
if(!process.argv.includes('--mobile-only'))await writeFile(`${dir}/validation-4a.json`,JSON.stringify({screenshots:results.length,results},null,2)+'\n');
