/** Trusted identity for operation tests; permissions.test exercises /me discovery. */
export const fullAccessIdentity = {
  account_id: "00000000-0000-4000-8000-000000000001",
  environment: "live" as const,
  scopes: [
  "agents:read",
  "agents:write",
  "calendar:read",
  "calendar:write",
  "comment-rules:read",
  "comment-rules:write",
  "messages:send",
  "messages:read",
  "events:read",
  "conversations:read",
  "conversations:write",
  "contacts:read",
  "contacts:write",
  "appointments:read",
  "appointments:write",
  "journeys:write",
  "journeys:read",
  "templates:read",
  "templates:write",
  "numbers:read",
  "numbers:write",
  "webhooks:read",
  "webhooks:write",
  "customers:read",
  "customers:write",
  "media:read",
  "media:write",
  "broadcasts:read",
  "broadcasts:write",
  "saved_replies:read",
  "saved_replies:write",
  "crm:read",
  "crm:write",
  "inbox:read",
  "inbox:write",
  "team:read",
  "logs:read"
],
};
